// <auto-generated />
using ECBATS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECBATS.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20211028083212_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("ECBATS.Data.CryptoSaving", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CryptoName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Percent24h")
                        .HasColumnType("TEXT");

                    b.Property<string>("Percent7j")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ID = "bitcoin",
                            CryptoName = "btc",
                            Image = "https://assets.coingecko.com/coins/images/1/large/bitcoin.png?1547033579",
                            Percent24h = "1.8497533421051617",
                            Percent7j = "-8.957777811272306}",
                            Price = "51735",
                            Symbol = "Bitcoin"
                        },
                        new
                        {
                            ID = "ethereum",
                            CryptoName = "eth",
                            Image = "https://assets.coingecko.com/coins/images/279/large/ethereum.png?1595348880",
                            Percent24h = "1.9497397418281153",
                            Percent7j = "-1.0337495464881228}",
                            Price = "3540.51",
                            Symbol = "Ethereum"
                        },
                        new
                        {
                            ID = "binancecoin",
                            CryptoName = "bnb",
                            Image = "https://assets.coingecko.com/coins/images/825/large/binance-coin-logo.png?1547034615",
                            Percent24h = "5.264158433080324",
                            Percent7j = "-5.025007946833159}",
                            Price = "409.93",
                            Symbol = "Binance Coin"
                        },
                        new
                        {
                            ID = "tether",
                            CryptoName = "usdt",
                            Image = "https://assets.coingecko.com/coins/images/325/large/Tether-logo.png?1598003707",
                            Percent24h = "1.6249345119997385",
                            Percent7j = "1.4230339557818743}",
                            Price = "0.870067",
                            Symbol = "Tether"
                        },
                        new
                        {
                            ID = "cardano",
                            CryptoName = "ada",
                            Image = "https://assets.coingecko.com/coins/images/975/large/cardano.png?1547034860",
                            Percent24h = "2.504403196375786",
                            Percent7j = "-8.3315486642433}",
                            Price = "1.73",
                            Symbol = "Cardano"
                        },
                        new
                        {
                            ID = "solana",
                            CryptoName = "sol",
                            Image = "https://assets.coingecko.com/coins/images/4128/large/Solana.jpg?1635329178",
                            Percent24h = "2.7943167656470966",
                            Percent7j = "11.504988307870914}",
                            Price = "167.98",
                            Symbol = "Solana"
                        },
                        new
                        {
                            ID = "ripple",
                            CryptoName = "xrp",
                            Image = "https://assets.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1605778731",
                            Percent24h = "4.928361648518545",
                            Percent7j = "-6.33583603300895}",
                            Price = "0.918881",
                            Symbol = "XRP"
                        },
                        new
                        {
                            ID = "polkadot",
                            CryptoName = "dot",
                            Image = "https://assets.coingecko.com/coins/images/12171/large/aJGBjJFU_400x400.jpg?1597804776",
                            Percent24h = "2.4200732739282964",
                            Percent7j = "-4.216442590082043}",
                            Price = "36.61",
                            Symbol = "Polkadot"
                        },
                        new
                        {
                            ID = "dogecoin",
                            CryptoName = "doge",
                            Image = "https://assets.coingecko.com/coins/images/5/large/dogecoin.png?1547792256",
                            Percent24h = "34.31770172740452",
                            Percent7j = "22.861671158261306}",
                            Price = "0.268272",
                            Symbol = "Dogecoin"
                        },
                        new
                        {
                            ID = "shiba-inu",
                            CryptoName = "shib",
                            Image = "https://assets.coingecko.com/coins/images/11939/large/shiba.png?1622619446",
                            Percent24h = "35.03007087755212",
                            Percent7j = "144.26406943036312}",
                            Price = "6.128e-05",
                            Symbol = "Shiba Inu"
                        },
                        new
                        {
                            ID = "usd-coin",
                            CryptoName = "usdc",
                            Image = "https://assets.coingecko.com/coins/images/6319/large/USD_Coin_icon.png?1547042389",
                            Percent24h = "0.8879354456476051",
                            Percent7j = "0.913571815745507}",
                            Price = "0.868303",
                            Symbol = "USD Coin"
                        },
                        new
                        {
                            ID = "terra-luna",
                            CryptoName = "luna",
                            Image = "https://assets.coingecko.com/coins/images/8284/large/luna1557227471663.png?1567147072",
                            Percent24h = "3.771259028386963",
                            Percent7j = "-2.713271174138225}",
                            Price = "35.72",
                            Symbol = "Terra"
                        },
                        new
                        {
                            ID = "chainlink",
                            CryptoName = "link",
                            Image = "https://assets.coingecko.com/coins/images/877/large/chainlink-new-logo.png?1547034700",
                            Percent24h = "1.9612954105958467",
                            Percent7j = "11.361027676265433}",
                            Price = "26.3",
                            Symbol = "Chainlink"
                        },
                        new
                        {
                            ID = "avalanche-2",
                            CryptoName = "AVAX",
                            Image = "https://assets.coingecko.com/coins/images/12559/large/coin-round-red.png?1604021818",
                            Percent24h = "1.7025520997930632",
                            Percent7j = "7.189509942003525}",
                            Price = "54.99",
                            Symbol = "Avalanche"
                        },
                        new
                        {
                            ID = "wrapped-bitcoin",
                            CryptoName = "wbtc",
                            Image = "https://assets.coingecko.com/coins/images/7598/large/wrapped_bitcoin_wbtc.png?1548822744",
                            Percent24h = "1.7255970100118498",
                            Percent7j = "-9.050120225947248}",
                            Price = "51655",
                            Symbol = "Wrapped Bitcoin"
                        },
                        new
                        {
                            ID = "binance-usd",
                            CryptoName = "busd",
                            Image = "https://assets.coingecko.com/coins/images/9576/large/BUSD.png?1568947766",
                            Percent24h = "1.4282146480147409",
                            Percent7j = "1.210537286073843}",
                            Price = "0.871305",
                            Symbol = "Binance USD"
                        },
                        new
                        {
                            ID = "uniswap",
                            CryptoName = "uni",
                            Image = "https://assets.coingecko.com/coins/images/12504/large/uniswap-uni.png?1600306604",
                            Percent24h = "1.7915549365985142",
                            Percent7j = "-7.326609603364504}",
                            Price = "21.52",
                            Symbol = "Uniswap"
                        },
                        new
                        {
                            ID = "litecoin",
                            CryptoName = "ltc",
                            Image = "https://assets.coingecko.com/coins/images/2/large/litecoin.png?1547033580",
                            Percent24h = "3.332938290329611",
                            Percent7j = "-9.582569379058747}",
                            Price = "161.09",
                            Symbol = "Litecoin"
                        },
                        new
                        {
                            ID = "matic-network",
                            CryptoName = "matic",
                            Image = "https://assets.coingecko.com/coins/images/4713/large/matic-token-icon.png?1624446912",
                            Percent24h = "11.632257002880527",
                            Percent7j = "25.43765069567633}",
                            Price = "1.65",
                            Symbol = "Polygon"
                        },
                        new
                        {
                            ID = "algorand",
                            CryptoName = "algo",
                            Image = "https://assets.coingecko.com/coins/images/4380/large/download.png?1547039725",
                            Percent24h = "1.3565172999200086",
                            Percent7j = "2.8018955753672925}",
                            Price = "1.58",
                            Symbol = "Algorand"
                        },
                        new
                        {
                            ID = "cosmos",
                            CryptoName = "atom",
                            Image = "https://assets.coingecko.com/coins/images/1481/large/cosmos_hub.png?1555657960",
                            Percent24h = "6.273840920065187",
                            Percent7j = "11.828937606861507}",
                            Price = "34.51",
                            Symbol = "Cosmos"
                        },
                        new
                        {
                            ID = "bitcoin-cash",
                            CryptoName = "bch",
                            Image = "https://assets.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1594689492",
                            Percent24h = "2.7052530776369026",
                            Percent7j = "-10.304833881545099}",
                            Price = "495.44",
                            Symbol = "Bitcoin Cash"
                        },
                        new
                        {
                            ID = "vechain",
                            CryptoName = "vet",
                            Image = "https://assets.coingecko.com/coins/images/1167/large/VeChain-Logo-768x725.png?1547035194",
                            Percent24h = "2.7465292623639415",
                            Percent7j = "7.887083119238239}",
                            Price = "0.113541",
                            Symbol = "VeChain"
                        },
                        new
                        {
                            ID = "fantom",
                            CryptoName = "ftm",
                            Image = "https://assets.coingecko.com/coins/images/4001/large/Fantom.png?1558015016",
                            Percent24h = "18.490172556076615",
                            Percent7j = "37.06610147126002}",
                            Price = "2.87",
                            Symbol = "Fantom"
                        },
                        new
                        {
                            ID = "stellar",
                            CryptoName = "xlm",
                            Image = "https://assets.coingecko.com/coins/images/100/large/Stellar_symbol_black_RGB.png?1552356157",
                            Percent24h = "1.363655034017778",
                            Percent7j = "-11.427766585980013}",
                            Price = "0.29794",
                            Symbol = "Stellar"
                        },
                        new
                        {
                            ID = "axie-infinity",
                            CryptoName = "axs",
                            Image = "https://assets.coingecko.com/coins/images/13029/large/axie_infinity_logo.png?1604471082",
                            Percent24h = "2.908265828635455",
                            Percent7j = "-0.07879243109175665}",
                            Price = "109.73",
                            Symbol = "Axie Infinity"
                        },
                        new
                        {
                            ID = "dai",
                            CryptoName = "dai",
                            Image = "https://assets.coingecko.com/coins/images/9956/large/dai-multi-collateral-mcd.png?1574218774",
                            Percent24h = "1.3555061498349052",
                            Percent7j = "1.3638020203438417}",
                            Price = "0.869889",
                            Symbol = "Dai"
                        },
                        new
                        {
                            ID = "internet-computer",
                            CryptoName = "icp",
                            Image = "https://assets.coingecko.com/coins/images/14495/large/Internet_Computer_logo.png?1620703073",
                            Percent24h = "2.1033087855925103",
                            Percent7j = "-6.5283283603311375}",
                            Price = "37.73",
                            Symbol = "Internet Computer"
                        },
                        new
                        {
                            ID = "ftx-token",
                            CryptoName = "ftt",
                            Image = "https://assets.coingecko.com/coins/images/9026/large/F.png?1609051564",
                            Percent24h = "0.40116109766854163",
                            Percent7j = "-2.7175857999012405}",
                            Price = "51.33",
                            Symbol = "FTX Token"
                        },
                        new
                        {
                            ID = "filecoin",
                            CryptoName = "fil",
                            Image = "https://assets.coingecko.com/coins/images/12817/large/filecoin.png?1602753933",
                            Percent24h = "3.240084789473717",
                            Percent7j = "-11.705658546982608}",
                            Price = "50.85",
                            Symbol = "Filecoin"
                        },
                        new
                        {
                            ID = "ethereum-classic",
                            CryptoName = "etc",
                            Image = "https://assets.coingecko.com/coins/images/453/large/ethereum-classic-logo.png?1547034169",
                            Percent24h = "9.16786432015224",
                            Percent7j = "-5.702466566712895}",
                            Price = "45.24",
                            Symbol = "Ethereum Classic"
                        },
                        new
                        {
                            ID = "tron",
                            CryptoName = "trx",
                            Image = "https://assets.coingecko.com/coins/images/1094/large/tron-logo.png?1547035066",
                            Percent24h = "4.179606334000939",
                            Percent7j = "-7.5415074078892586}",
                            Price = "0.082178",
                            Symbol = "TRON"
                        },
                        new
                        {
                            ID = "compound-ether",
                            CryptoName = "ceth",
                            Image = "https://assets.coingecko.com/coins/images/10643/large/ceth2.JPG?1581389598",
                            Percent24h = "1.4769305783640105",
                            Percent7j = "-1.2679907705517892}",
                            Price = "70.82",
                            Symbol = "cETH"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
